# .github/workflows/main.yml

name: Test & Lint

on:
  workflow_call:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    strategy:
      matrix:
        go: [1.24.x, 1.23.x, 1.22.x, 1.21.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: |
            go.sum
            tools/go.sum
      - run: make test
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Go ${{  matrix.go }} Test Results
          path: .test/reports/**-test.xml
          reporter: java-junit
          fail-on-error: "true"
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Test Report ${{  matrix.go }}
          path: .test/reports/**

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
          cache-dependency-path: |
            tools/go.sum
      - run: make lint
