# .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: zeiss/pkg
  REGISTRY: ghcr.io
      
jobs:
  test:
    permissions:
      checks: write
    uses: ./.github/workflows/main.yml

  release:
    runs-on: ubuntu-latest
    needs: [ test ]
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./tools/go.mod
          cache-dependency-path: |
            go.sum
            tools/go.sum
      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - run: make release
        if: success()